build: Go 1.15
storj/storj pull request #3927
Opened 2020-08-12 15:38 UTC by brimstone

What: Update to go 1.15

Why: Update are generally good.

Please describe the tests: no additional tests.

Please describe the performance impact: Non expected. Might even be a
little faster.

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible?
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/master/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/master/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

2020-08-12 15:40 UTC, cam-a submitted a review, later dismissed

2020-09-06 05:22 UTC, egonelbre approved these changes

2020-09-07 12:06 UTC, stefanbenten requested changes
Lets directly use v1.15.1

2020-09-07 12:54 UTC, stefanbenten approved these changes

2020-09-07 13:01 UTC, egonelbre approved these changes

2020-09-07 13:01 UTC, merged