satellite/satellitedb: add columns for professional users
storj/storj pull request #4028
Opened 2021-01-21 21:46 UTC by mbouzi

What: Add columns for professional users

Why: needs need fields for users for new professional tab during signup process 

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

2021-01-21 21:50 UTC, egonelbre requested changes

2021-01-21 21:50 UTC, egonelbre commented on satellite/satellitedb/dbx/satellitedb.dbx
> +    field is_professional              bool      ( updatable, default false )
follow the formatting above

2021-01-21 21:50 UTC, egonelbre commented on satellite/satellitedb/migrate.go
> +                    `ALTER TABLE users ADD COLUMN is_professional boolean NOT NULL DEFAULT false;`,
Follow the formatting of Go code.

2021-01-21 21:50 UTC, egonelbre commented on satellite/satellitedb/testdata/postgres.v140.sql
> +-- NEW DATA --
Add data to have the new columns.

2021-01-25 21:30 UTC, egonelbre submitted a review, later dismissed

2021-01-26 15:24 UTC, mobyvb approved these changes

2021-01-26 16:07 UTC, egonelbre approved these changes

2021-01-26 16:38 UTC, merged