Access Grant Wizard Copy Edits
storj/storj pull request #4066
Opened 2021-03-19 12:49 UTC by boshevski

Update subheader copy to say:

Run the setup command in the uplink CLI and input the satellite address and token below when prompted to generate your access grant.

What: 

Why:

Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

2021-03-19 12:50 UTC, VitaliiShpital approved these changes

2021-03-19 14:05 UTC, mbouzi submitted a review, later dismissed
👍

2021-03-19 16:23 UTC, egonelbre requested changes

2021-03-19 16:23 UTC, egonelbre commented on web/satellite/src/components/accessGrants/steps/CLIStep.html
>      <BackIcon class="cli-container__back-icon" @click="onBackClick"/>
Fix the commit message to use a folder/context prefix

2021-03-22 11:14 UTC, egonelbre approved these changes

2021-03-22 11:20 UTC, VitaliiShpital approved these changes

2021-03-31 15:03 UTC, merged