docs/testplan: Testplan for Session Management
storj/storj pull request #4800
Opened 2022-05-12 13:17 UTC by nadimhq

This testplan covers security must haves regarding session management
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

2022-09-13 14:13 UTC, storj-antonio approved these changes
LGTM

2022-10-10 11:57 UTC, littleskunk requested changes

2022-10-10 11:57 UTC, littleskunk commented on docs/testplan/session-management.md
> +|                   | New IP Address         | If a session is created from a new IP(different than previous session), then there should be two-factor authentication to verify the user
Was that in the design document? I don't think we implemented like this.

2022-10-10 11:57 UTC, littleskunk commented on docs/testplan/session-management.md
> +|                   | Reset Password         | If a user resets their password, then all sessions should be invalidated once the user successfully resets their password
Reset password is the only one that should invalidate all sessions. Logout, inativity timer and closing the browser should only invalidate the current but not all sessions.

2022-10-11 23:08 UTC, storj-antonio approved these changes

2022-10-13 23:47 UTC, littleskunk approved these changes

2022-10-14 00:20 UTC, merged