web/satellite/vuetify-poc: ui ux improvements
storj/storj pull request #6472
Opened 2023-11-02 13:52 UTC by boshevski

What: 
Improving the satellite v2 user interface and overall experience.
 
Why:
Continuous improvements to polish everything in v2.

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

2023-11-02 15:59 UTC, jewharton requested changes

2023-11-02 15:59 UTC, jewharton commented on web/satellite/vuetify-poc/src/components/TeamTableComponent.vue
> +        <div v-if="selectedMembers.length" cols="auto">
This button is positioned above the search field instead of beside it.

2023-11-02 15:59 UTC, jewharton commented on web/satellite/vuetify-poc/src/components/billing/BillingHistoryTab.vue
> +    <v-card :border="true" rounded="xlg">
Should this table have the same styling as the team, buckets, files, and projects tables?

2023-11-02 15:59 UTC, jewharton commented on web/satellite/vuetify-poc/src/components/TokenTransactionsTableComponent.vue
> +    <v-card :border="true" rounded="xlg">
Should this table have the same styling as the team, buckets, files, and projects tables?

2023-11-02 17:05 UTC, boshevski commented on web/satellite/vuetify-poc/src/components/TokenTransactionsTableComponent.vue
> +    <v-card :border="true" rounded="xlg">
It's the same, doesn't really change anything.

2023-11-02 17:05 UTC, boshevski commented on web/satellite/vuetify-poc/src/components/billing/BillingHistoryTab.vue
> +    <v-card :border="true" rounded="xlg">
It's the same, doesn't really change anything.

2023-11-02 17:24 UTC, boshevski commented on web/satellite/vuetify-poc/src/components/TeamTableComponent.vue
> +        <div v-if="selectedMembers.length" cols="auto">
Thank you Jeremy, i missed this one. Fixed now.

2023-11-02 17:35 UTC, wilfred-asomanii commented on web/satellite/vuetify-poc/src/components/dialogs/createAccessSteps/ChoosePermissionsStep.vue
> +                </v-chip-group> -->
NIT - this can be removed.

2023-11-02 17:36 UTC, wilfred-asomanii commented on web/satellite/vuetify-poc/src/components/dialogs/createAccessSteps/ChoosePermissionsStep.vue
> +                </v-chip-group> -->
NIT - this can also be removed

2023-11-02 17:42 UTC, wilfred-asomanii requested changes

2023-11-02 17:42 UTC, wilfred-asomanii commented on web/satellite/vuetify-poc/src/components/dialogs/upgradeAccountFlow/InfoBullet.vue
> +                    class="mr-3 opacity-100"
NIT - this looks very light, but I defer to your preference

2023-11-02 17:56 UTC, boshevski commented on web/satellite/vuetify-poc/src/components/dialogs/createAccessSteps/ChoosePermissionsStep.vue
> +                </v-chip-group> -->
This is left for reference as part of next update for the access grants flow.

2023-11-02 17:59 UTC, jewharton submitted a review, later dismissed

2023-11-03 10:10 UTC, wilfred-asomanii approved these changes

2023-11-03 15:00 UTC, jewharton approved these changes

2023-11-09 19:35 UTC, jewharton commented
This PR has been moved to Gerrit: https://review.dev.storj.io/c/storj/storj/+/11702

2023-11-09 19:35 UTC, closed without merging